const CommentConstants = {
  ADD_COMMENT: 'ADD_COMMENT',
  DELETE_COMMENT: 'DELETE_COMMENT',
  EDIT_COMMENT: 'EDIT_COMMENT',
  LIKE_COMMENT: 'LIKE_COMMENT',
  UNLIKE_COMMENT: 'UNLIKE_COMMENT',
};

export default CommentConstants;
